### ISSUE TITLE
Enhancement proposal: Overhauling 'src' structure with packages, subpackages and modules.

### ISSUE THREAD

**Issue by ejgenc** [europeana/rd-europeana-python-api#10]
## Proposal

While overhauling the overall repository structure,  it occured to me that we could actually lay out our codebase in terms of packages and subpackages.

We currently only have 'pyeuropeana' under 'src', as it should be per standarts. 'pyeuropeana' is the name of the package, and under the package we have two modules: 'apis.py' and 'utils.py'. While this currently works, it might start cluttering as we wrap more of Europeana's api and add additional utility functions. We can preemptively go for a more fragmented package structure. For example:

- We can start using subpackages. The 'pyeuropeana' package can have under it two more folders: 'apis' and 'utils'. 
 - the 'apis' folder would have under it two Python files: 'search.py' and 'records.py'. The contents of these files would come from the current 'apis.py' and 'apis.py' can be deleted.
 - The 'utils' folder can have under it Python files that we categorize according to what exact utility the containing code covers: For exampel: 'url_utils' for utils related to urls, 'image_utils' for utils related to urls and 'bulk_download' utils for utils related to 

### Advantages

This would give our codebase a more logical structure as we start expanding the functionality. The documentation would look more organized, and if we lay out an intuitive structure the users can easily find their ways around the package.

### Disadvantages

This approach is too verbose for our current scale. It would also require us to retroactively edit all the imports in the notebooks.

@joseed-europeana what do you think? The verbosity is real, but it might be too hard to split things hard once (or if) the codebase grows.

**Comment by ejgenc** [comment]
Great! I agree with the second version being the preferred one. It seems to be in a sweet spot in between "dump all on import" and "import everything individually" approach. However, I don't think I quite managed to communicate effectively what I've meant with packaged and subpackages. I am drafting up a pull request ATM. Perhaps we can talk over that and review it as we see fit to allow imports with the 2nd import style

**Comment by ejgenc** [comment]
Pull request #12 makes concrete what I propose with this issue. I'd like to introduce some discussion points below:

- Such a subpackage structure would allow us see a clearer picture of our development efforts: Europeana has different API's, and we are writing wrappers for some of those APIs. Therefore, we have a different .py file for each API. Ideally the number of .py files will increase as we add more and more API coverage. Currently there exists only one class inside each .py, but we can add more and more functionality and increase them in size.

- However, modularity seems to come at a cost. I identified two ways in which we can promote importing different subpackages:
<img width="251" alt="way-1" src="https://user-images.githubusercontent.com/33980760/153852417-f096df48-754f-4c5c-9183-aa31fb02b033.png">

The first way outlined above has us importing functionalities piece by piece from their respective subpackages and modules. While we can call them in one liners within the actual code base, you'd have to handpick everything one by one as first thing. That can get quite verbose.
<img width="299" alt="way-2" src="https://user-images.githubusercontent.com/33980760/153853372-92bc8a13-11df-4481-83b8-c22cd2ce7180.png">

The second way outlined above is less verbose at first. We can promote mass import of packages ("all Search methods/classes" or "all image utility functions"), but then we might have to change the wording around how we actually promote the use of package.  For example:

```python
search_api = search_api.Search("api2demo")
```

The line above has two problems:

- We are overriding the import that was also called search_api
- search_api.Search sounds...weird? It sounds more like a function than an object instance, and that's not what it is.

Maybe we can think of renaming the objects and modules. "Search" class can be called "SearchWrapper" or "SearchInterface".

```python
import pyeuropena.apis.search as pyesearch

search_wrapper = pyesearch.SearchWrapper("api2demo")
response = search_wrapper(...)
```

@joseed-europeana What do you think?

**Comment by joseed-europeana** [comment]
Thanks for raising this, naming can be an issue. Your suggestion can be an improvement, but I see that the pyesearch and pyerecord modules might only contain the SearchWrapper class so it might be redundant, see the example below

```
import pyeuropena.apis.search as pyesearch
import pyeuropena.apis.record as pyerecord

search_wrapper = pyesearch.SearchWrapper("api2demo")
record_wrapper = pyerecord.RecordWrapper("api2demo")

response = search_wrapper(...)
```

A possibility to avoid this redundancy could be to use the absolute import for the SearchWrapper and RecordWrapper classes, which in theory would only need to be done once per script (this works with the current implementation)

```
import pyeuropeana
from pyeuropeana.utils import resp2df

search_api = pyeuropeana.apis.SearchWrapper('api2demo')
record_api = pyeuropeana.apis.RecordWrapper('api2demo')

res = search_api(q = '*')
df = resp2df(res)
```

A simpler possibility would be the following one (this works with the current implementation)

```
from pyeuropeana.apis import SearchAPI, RecordAPI
from pyeuropeana.utils import resp2df

search_api = SearchAPI('api2demo')
record_api = RecordAPI('api2demo')

res = search_api(q = '*')
df = resp2df(res)
```
At the end it might be a matter of taste and it might be difficult to take a decision now without feedback from the potential users. I suggest we use the last option for now, but bear in mind we might have to choose a different option in the future

**Comment by joseed-europeana** [comment]
Sorry, the last two options work with the stable branch. With the current structure of the repo it is enough to add 

```
from .entity import Entity
from .search import Search
from .record import Record
```

to the __init__.py file in the api folder

**Comment by ejgenc** [comment]
I don't know anything about adding imports into the __init__.py file. Can you link some documentation as to what this will enable?

**Comment by ejgenc** [comment]
I will study this and try to understand what it exactly does. I am fine with you implemeting the necessary changes if you want, I'll just update the branch that I am working on accordingly.

**Comment by ejgenc** [comment]
I think that we settled on the subpackage approach. Closing the issue now.
