### ISSUE TITLE
duplicate items

### ISSUE THREAD

**Issue by paoloeuropeana** [europeana/rd-europeana-python-api#4]
Hi Jose,

While using the python search API I noticed that when I use a high number of rows for the queries (n_rows>100) 
I obtain several duplicated items (also same IDs). I think it maybe related to the next_cursor, have you ever observed it?

Also I noticed that the total number of results is not always repeatable (I run the code multiple times), the returned number fluctuates when the n_rows is high

Paolo

**Comment by ejgenc** [comment]
@paoloeuropeana  @joseed-europeana  I remember that this issue was solved with a hotfix. Do I remember correctly? If so, I'll close this issue.

**Comment by ejgenc** [comment]
Issue closed after our discussion with @joseed-europeana. See also #7.
